'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property CustomreID As String
    Public Property ArName As String
    Public Property EnName As String
    Public Property Telephone As String
    Public Property Fax As String
    Public Property Address As String
    Public Property ActiveCustomer As String
    Public Property ModDate As Date
    Public Property ModUser As String

End Class
