'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Doc
    Public Property SessionDate As Date
    Public Property AttachmentID As Integer
    Public Property DOCID As String
    Public Property FileContents As Byte()
    Public Property FileExt As String
    Public Property Failed As Boolean
    Public Property FailedError As String
    Public Property Uploaded As Boolean
    Public Property UploadedCounter As Integer
    Public Property SAP_FileName As String
    Public Property ModDate As Date
    Public Property ModUser As String
    Public Property Status As Short
    Public Property ReviewedBy As String

End Class
