'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Driver
    Public Property DriverID As Integer
    Public Property TransporterID As Integer
    Public Property ArName As String
    Public Property EnName As String
    Public Property Mobile As String
    Public Property Moduser As String
    Public Property ModDate As Date
    Public Property SAP_CODE As String

End Class
