'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOG_DOCS
    Public Property trDt As Date
    Public Property C___operation As Integer
    Public Property SessionDate As Date
    Public Property AttachmentID As Integer
    Public Property DOCID As String
    Public Property Moddate As Nullable(Of Date)
    Public Property ModUser As String

End Class
