'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOG_SAP_DOCS_HDR
    Public Property trDt As Date
    Public Property C___operation As Integer
    Public Property DocID As String
    Public Property DriverID As Nullable(Of Integer)
    Public Property Drvr_SAP_CODE As String
    Public Property DriverName As String
    Public Property DriverMobile As String
    Public Property TransporterID As Nullable(Of Integer)
    Public Property Trns_SAP_CODE As String
    Public Property PlateNumber As String
    Public Property TrucksRelease As Nullable(Of Date)
    Public Property CustomerRecieve As Nullable(Of Date)
    Public Property ModUser As String
    Public Property ModDate As Nullable(Of Date)

End Class
