'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities_POD
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities_POD")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property SAP_DOCs_HDR() As DbSet(Of SAP_DOCs_HDR)
    Public Property Customers() As DbSet(Of Customer)
    Public Property Drivers() As DbSet(Of Driver)
    Public Property Transporters() As DbSet(Of Transporter)
    Public Property LOG_DOCS() As DbSet(Of LOG_DOCS)
    Public Property Docs() As DbSet(Of Doc)
    Public Property Users() As DbSet(Of User)
    Public Property LOG_SAP_DOCS_HDR() As DbSet(Of LOG_SAP_DOCS_HDR)
    Public Property TransporterInvFiles() As DbSet(Of TransporterInvFile)
    Public Property TransporterInvHDRs() As DbSet(Of TransporterInvHDR)

End Class
