'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SAP_DOCs_HDR
    Public Property DocID As String
    Public Property PoNumber As String
    Public Property OrderNo As String
    Public Property DocDate As Date
    Public Property DocDateHijri As String
    Public Property PlantID As String
    Public Property SourceID As String
    Public Property CustomerID_Billto As String
    Public Property CustomerID_ShipTo As String
    Public Property DriverID As Integer
    Public Property PlateNumber As String
    Public Property TrucksRelease As Date
    Public Property CustomerRecieve As Date
    Public Property Completed As Boolean
    Public Property ModUser As String
    Public Property ModDate As Date
    Public Property Trns_SAP_CODE As String
    Public Property Drvr_SAP_CODE As String
    Public Property TransporterID As Integer
    Public Property DriverName As String
    Public Property DriverMobile As String
    Public Property PGIDate As Nullable(Of Date)
    Public Property ExistsSAP As Nullable(Of Boolean)
    Public Property TrnsRefInv As String
    Public Property Status As Short
    Public Property ReviewedBy As String
    Public Property OverNightReason As Integer

End Class
