'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transporter
    Public Property TransporterID As Integer
    Public Property ArName As String
    Public Property EnName As String
    Public Property Telephone As String
    Public Property ModDate As Date
    Public Property ModUser As String
    Public Property SAP_CODE As String
    Public Property ReqInvCd As Boolean

End Class
