'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TransporterInvFile
    Public Property Year As String
    Public Property ID As Integer
    Public Property SEQID As Integer
    Public Property FileContents As Byte()

End Class
