'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property UserName As String
    Public Property Password As Byte()
    Public Property Name As String
    Public Property AppAuth As Boolean
    Public Property ResetPassword As Boolean
    Public Property Lock As Boolean
    Public Property LockCount As Integer
    Public Property Admin As Boolean
    Public Property Report As Boolean
    Public Property Active As Boolean
    Public Property ModDate As Date
    Public Property ModUser As String

End Class
